
CREATE TABLE public.storefront_settings (
  id TEXT PRIMARY KEY DEFAULT 'default',
  business_name TEXT NOT NULL DEFAULT 'PetDash Pro',
  tagline TEXT DEFAULT 'Premium pet care tailored to every furry friend',
  logo_url TEXT,
  favicon_url TEXT,
  hero_style TEXT NOT NULL DEFAULT 'gradient',
  hero_headline TEXT DEFAULT 'Our Services',
  hero_subheadline TEXT DEFAULT 'Premium pet care tailored to every furry, feathered & scaly friend',
  hero_media_url TEXT,
  hero_video_url TEXT,
  hero_cta_label TEXT DEFAULT 'Book now',
  hero_cta_link TEXT DEFAULT '#services',
  hero_cta_secondary_label TEXT,
  hero_cta_secondary_link TEXT,
  theme_preset TEXT NOT NULL DEFAULT 'lime',
  primary_color TEXT DEFAULT 'hsl(75 95% 50%)',
  accent_color TEXT DEFAULT 'hsl(0 0% 8%)',
  hero_gradient_from TEXT DEFAULT '#0f172a',
  hero_gradient_to TEXT DEFAULT '#1e293b',
  font_family TEXT DEFAULT 'Plus Jakarta Sans',
  radius_scale TEXT DEFAULT 'md',
  announcement_enabled BOOLEAN NOT NULL DEFAULT false,
  announcement_text TEXT DEFAULT '',
  announcement_bg TEXT DEFAULT '#111111',
  announcement_fg TEXT DEFAULT '#f5f5f5',
  announcement_link TEXT,
  trust_badges JSONB NOT NULL DEFAULT '[{"icon":"Star","text":"4.9★ Rated"},{"icon":"Heart","text":"500+ Happy Pets"},{"icon":"Award","text":"Certified Pros"}]'::jsonb,
  about_title TEXT DEFAULT 'About us',
  about_body TEXT DEFAULT 'We are passionate about pets and dedicated to giving them the best care possible.',
  about_image_url TEXT,
  about_video_url TEXT,
  years_in_business INTEGER,
  pets_served INTEGER,
  gallery_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  gallery_layout TEXT DEFAULT 'masonry',
  team_members JSONB NOT NULL DEFAULT '[]'::jsonb,
  business_hours JSONB NOT NULL DEFAULT '{"monday":{"open":"09:00","close":"18:00","closed":false},"tuesday":{"open":"09:00","close":"18:00","closed":false},"wednesday":{"open":"09:00","close":"18:00","closed":false},"thursday":{"open":"09:00","close":"18:00","closed":false},"friday":{"open":"09:00","close":"18:00","closed":false},"saturday":{"open":"10:00","close":"16:00","closed":false},"sunday":{"open":"10:00","close":"16:00","closed":true}}'::jsonb,
  contact_phone TEXT,
  contact_email TEXT,
  contact_address TEXT,
  map_embed_url TEXT,
  social_instagram TEXT,
  social_facebook TEXT,
  social_tiktok TEXT,
  social_youtube TEXT,
  social_whatsapp TEXT,
  social_x TEXT,
  social_google TEXT,
  instagram_feed_enabled BOOLEAN NOT NULL DEFAULT false,
  instagram_handle TEXT,
  faqs JSONB NOT NULL DEFAULT '[]'::jsonb,
  press_logos JSONB NOT NULL DEFAULT '[]'::jsonb,
  certifications JSONB NOT NULL DEFAULT '[]'::jsonb,
  awards JSONB NOT NULL DEFAULT '[]'::jsonb,
  cancellation_policy TEXT,
  refund_policy TEXT,
  privacy_policy_url TEXT,
  terms_url TEXT,
  vaccination_policy TEXT,
  newsletter_enabled BOOLEAN NOT NULL DEFAULT true,
  newsletter_headline TEXT DEFAULT 'Get 10% off your first booking',
  newsletter_subheadline TEXT DEFAULT 'Join our pack for tips, updates & members-only offers.',
  popup_enabled BOOLEAN NOT NULL DEFAULT false,
  popup_headline TEXT,
  popup_body TEXT,
  popup_cta_label TEXT,
  popup_cta_link TEXT,
  popup_image_url TEXT,
  loyalty_teaser_enabled BOOLEAN NOT NULL DEFAULT true,
  loyalty_teaser_text TEXT DEFAULT 'Earn points on every booking. Redeem for free grooms.',
  section_visibility JSONB NOT NULL DEFAULT '{"announcement":true,"hero":true,"trust":true,"festivals":true,"promos":true,"featured_services":true,"categories":true,"services":true,"memberships":true,"packages":true,"gallery":true,"about":true,"team":true,"reviews":true,"faq":true,"hours":true,"map":true,"contact":true,"newsletter":true,"social":true,"press":true,"certifications":true,"loyalty":true,"instagram":false}'::jsonb,
  section_order JSONB NOT NULL DEFAULT '["announcement","hero","trust","festivals","promos","featured_services","categories","services","memberships","packages","gallery","about","team","reviews","faq","hours","map","contact","newsletter","instagram","press","certifications","loyalty","social"]'::jsonb,
  meta_title TEXT,
  meta_description TEXT,
  og_image_url TEXT,
  google_analytics_id TEXT,
  meta_pixel_id TEXT,
  currency TEXT DEFAULT 'EUR',
  timezone TEXT DEFAULT 'Europe/Madrid',
  languages JSONB NOT NULL DEFAULT '["en"]'::jsonb,
  custom_css TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.storefront_settings TO authenticated, anon;
GRANT ALL ON public.storefront_settings TO service_role;
ALTER TABLE public.storefront_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read storefront_settings" ON public.storefront_settings FOR SELECT USING (true);
CREATE POLICY "Allow public write storefront_settings" ON public.storefront_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update storefront_settings" ON public.storefront_settings FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete storefront_settings" ON public.storefront_settings FOR DELETE USING (true);
CREATE TRIGGER trg_storefront_settings_updated BEFORE UPDATE ON public.storefront_settings FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
INSERT INTO public.storefront_settings (id) VALUES ('default') ON CONFLICT (id) DO NOTHING;
